name = "Expedition Guild Stellar Frontier"
author = "gastercat"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "97fc100b4ba266d4b5359ee61af48748b8c1bf4b0970e636aa4fc47c12fc063c"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
