name = "Expedition Guild Stellar Frontier"
author = "gastercat"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9d2b4ff3ed8d5e8b25e75604850c8bc99982ceeba857eb49c2794c25d92644f4"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
