name = "Expedition Guild Stellar Frontier"
author = "gastercat"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b746e5c5816b283cf288bfac083ff96de5e26c1900702e05973404f551c4d309"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
